### ISSUE TITLE
Recommended approach to updating react components

### ISSUE THREAD

**Issue by ryanking1809** [alloc/ople#10]
I'm rebuilding the standard [redux todo-mvc](https://codesandbox.io/s/github/codesandbox/integration-sandboxes/tree/master/reduxjs-redux-examples-todomvc) in Ople here https://codesandbox.io/s/todomvc-8fb7u

And I'm at a point where I need to update react components on change. 
What's the recommended approach for this?

Is it by emitting and listening to events with `useEvents`?
Or is there some sort `useAuto` like function, similar to `wana`?  (It doesn't seem like I can use wana's withAuto)

Are `Ople` objects observable? Maybe I'm just assuming that because I know it's built on `wana`.

**Comment by aleclarson** [comment]
You can use `withAuto`, but make sure any nested objects (like the `TodoCollection.todos` object in your sandbox) are wrapped with `o` so their changes are observable.

**Comment by ryanking1809** [comment]
Makes sense, and works! (maybe I was getting a sandbox anomaly before)

**Comment by ryanking1809** [comment]
Additionally, `useEvents` listeners will auto-dispose if the source is disposed, correct?
But `withAuto` listeners will not have this behaviour? Is that right?

**Comment by aleclarson** [comment]
The `auto` function exported by `ople` **does** have automatic disposal, as long as it's called within an Ople context.

**Comment by ryanking1809** [comment]
Thanks! I'm getting a feel for it now. My general approach is to use `auto` within an Ople context to watch for changes and emit events. And only ever listen to emitted events using `.on()` outside the Ople context to utilise auto-disposal.

**Comment by aleclarson** [comment]
Quick note about the `useChange` hook in your sandbox:
```js
import { useState, useEffect } from "react";

export function useChange(source, prop) {
  const [reactState, setReactState] = useState(source[prop]);
  useEffect(() => {
    source.on(prop, () => {
      setReactState(source[prop]);
    });
  }, [source, prop]);
  return reactState;
}
```

First off, the `source.on` call is never cleaned up, resulting in a memory leak.

Also, if a change occurs between render phase and "commit" phase (eg: when `useEffect` callback is run), it won't be observed by your component. The `withAuto` HOC accounts for such an edge case, so I would recommend either using `withAuto` instead or adapt its code into your `useChange` hook. But if you're not hitting this edge case currently, I guess you can wait until you do.

Btw, `useChange` can be implemented without Ople events, if that's all you're using your `emitChange` mixin for. You can use wana's observer system instead.

```js
import { useState, useEffect } from "react";
import { $O } from "ople";

export function useChange(source, prop) {
  const [reactState, setReactState] = useState(source[prop]);
  useEffect(() => {
    const observable = source[$O];
    if (observable) {
      const slot = observable.get(prop);
      const observer = {
        onChange: () => setReactState(source[prop]),
      };
      slot.add(observer);
      return () => slot.delete(observer);
    }
  }, [source, prop]);
  return reactState;
}
```

### Tips for mixins

Don't forget that Ople mixins are **not** subject to the same rules as React hooks. For example, you can use Ople mixins within a loop, so your `emitChange` mixin could be `emitChanges(['a', 'b', 'c'])` if you wanted. You can even use Ople mixins conditionally. Lastly, mixins can use `getOple` or `expectOple` to avoid the need of taking the Ople object as an argument.

```js
import { auto, expectOple } from "ople";

export function emitChanges(propNames) {
  const self = expectOple();
  propNames.forEach(propName =>
    auto(() => {
      // just for listening
      const prop = self[propName];
      self.emit(propName);
    }));
}
```

**Comment by ryanking1809** [comment]
Oh, that's very helpful thanks! 

And does the `useEvents` hook suffer from the same edge case? eg. Could I do this instead?
```js
export function useChange(source, prop) {
  const [reactState, setReactState] = useState(source[prop]);
  let onEvent = {};
  const eventCallback = useCallback(() => setReactState(source[prop]), []);
  onEvent[prop] = eventCallback;
  useEvents(source, onEvent);
  return reactState;
}
```

**Comment by aleclarson** [comment]
`useEvents` has the same defect, though I might fix it at some point.

The solution is to postpone events until all pending `useEvents` calls are mounted. Then, the events can propagate without fear of being missed by a component that needs it. In my experience, it's rare for a missed event to break a component. Usually that's a sign of bad component design.

But for something like `useChange`, where a missed change would likely lead to stale data being displayed to the user, I would say it's crucial that changes not be missed.

**Comment by ryanking1809** [comment]
Oh good to know, I'll keep an eye out for that, and there's probably no reason not to just go with `withAuto`. There's just something I like about being able to explicitly say this component will only update on these events.

Thanks!
