### ISSUE TITLE
Auto-emit events

### ISSUE THREAD

**Issue by ryanking1809** [alloc/ople#8]
I'm not sure if should sit in the realm of the user, and possibly has performance implications, but for my use case, I would typically like to fire an event each time an Ople object's property / attribute changes (and create / dispose events). Without it a find myself subscribing to changes using `wana` and it might be nicer to have it built into `Ople` - should be easy to automate regardless so no biggie.

**Comment by aleclarson** [comment]
As you said, using `globals.onChange` is easy enough.

```js
import {globals, Ople} from 'ople'

globals.onChange = change => {
  if (change.target instanceof Ople) {
    change.target.emit('change', change)
  }
}
```

**Comment by ryanking1809** [comment]
Awesome, thanks!
